# Generated by Django 6.1 on 2026-08-09 05:39

import core.utilities.validators
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity', models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)])),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('activeyear', 'classroom__mainclassroom', 'classroom__name'),
            },
        ),
        migrations.CreateModel(
            name='ActiveClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activeclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activeclass')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activeclass',
            name='activeyear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activeyear'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('thumbnail', models.ImageField(upload_to='albums/', validators=[core.utilities.validators.validate_logo])),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('tahun', models.CharField(default='2026', max_length=4)),
                ('logo', models.ImageField(upload_to='brand/', validators=[core.utilities.validators.validate_logo])),
                ('instagram', models.URLField(default='https://www.instagram.com/hamdayuwafii/')),
                ('youtube', models.URLField(default='https://www.youtube.com/@hamdayuwafii')),
                ('tiktok', models.URLField(default='https://www.tiktok.com/@hamdayuwafii')),
                ('facebook', models.URLField(default='https://web.facebook.com/hamdayuwafii/')),
                ('developer', models.CharField(default='Hamdan Yuwafi', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('thumbnail', models.ImageField(upload_to='articles/', validators=[core.utilities.validators.validate_logo])),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('mainclassroom', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
                ('name', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('activeyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activeyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom')),
            ],
            options={
                'ordering': ('activeyear', 'classroom__mainclassroom', 'classroom__name'),
            },
        ),
        migrations.AddField(
            model_name='activeclass',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom'),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('body', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.article')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(choices=[('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('F5', 'F5')], max_length=2)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.activeclassstudent')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.activesubject')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('teacher', 'student', 'type'),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='pages/', validators=[core.utilities.validators.validate_logo])),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Nomor telepon tidak valid. Gunakan format Indonesia (08xx...).', regex='^(\\+62|62|0)8[1-9][0-9]{6,10}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/', validators=[core.utilities.validators.validate_logo])),
                ('npsn', models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='NPSN harus terdiri dari 8 digit angka.', regex='^\\d{8}$')])),
                ('status', models.CharField(blank=True, choices=[('Negeri', 'Negeri'), ('Swasta', 'Swasta')], max_length=20, null=True)),
                ('jenjang', models.CharField(blank=True, choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('SMK', 'SMK')], max_length=10, null=True)),
                ('akreditasi', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('Unggul', 'Unggul'), ('Baik Sekali', 'Baik Sekali'), ('Baik', 'Baik'), ('Tidak Terakreditasi', 'Tidak Terakreditasi')], max_length=20, null=True)),
                ('kepala_sekolah', models.CharField(blank=True, max_length=255, null=True)),
                ('nip_kepsek', models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(message='NIP harus terdiri dari 18 digit angka.', regex='^\\d{18}$')])),
                ('fax', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Nomor fax tidak valid. Gunakan hanya angka dan strip (misal 021-123456).', regex='^[\\d\\-]{5,15}$')])),
                ('kode_pos', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Kode pos harus terdiri dari 5 digit angka.', regex='^\\d{5}$')])),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activeyear',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('nomor_hp', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Nomor telepon tidak valid. Gunakan format Indonesia (08xx...).', regex='^(\\+62|62|0)8[1-9][0-9]{6,10}$')])),
                ('nisn', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='NISN harus terdiri dari 10 digit angka.', regex='^\\d{10}$')])),
                ('job', models.CharField(choices=[('Siswa', 'Siswa')], default='Siswa', editable=False, max_length=20)),
                ('status', models.CharField(blank=True, choices=[('Aktif', 'Aktif'), ('Lulus', 'Lulus'), ('Keluar', 'Keluar')], default='Aktif', max_length=10, null=True)),
                ('nis', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='NIS harus terdiri dari 10 digit angka.', regex='^\\d{10}$')])),
                ('nama_ayah', models.CharField(blank=True, max_length=255, null=True)),
                ('nama_ibu', models.CharField(blank=True, max_length=255, null=True)),
                ('nomor_hp_ortu', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Nomor telepon tidak valid. Gunakan format Indonesia (08xx...).', regex='^(\\+62|62|0)8[1-9][0-9]{6,10}$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActiveClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('activeyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activeyear')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
                ('students', models.ManyToManyField(blank=True, to='core.student')),
            ],
            options={
                'ordering': ('activeyear', 'club__name'),
            },
        ),
        migrations.AddField(
            model_name='activeclassstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AddField(
            model_name='activeclass',
            name='students',
            field=models.ManyToManyField(blank=True, through='core.ActiveClassStudent', to='core.student'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(choices=[('PKN', 'Pendidikan Kewarganegaraan'), ('BIND', 'Bahasa Indonesia'), ('BIG', 'Bahasa Inggris'), ('MAT', 'Matematika'), ('IPA', 'Ilmu Pengetahuan Alam'), ('IPS', 'Ilmu Pengetahuan Sosial'), ('SBK', 'Seni Budaya'), ('PJOK', 'Pendidikan Jasmani Olahraga dan Kesehatan'), ('PRAKARYA', 'Prakarya'), ('TIK', 'Teknologi Informasi dan Komunikasi'), ('MULOK', 'Muatan Lokal'), ('PAI', 'Pendidikan Agama Islam'), ('PAK', 'Pendidikan Agama Kristen'), ('PAKH', 'Pendidikan Agama Katolik'), ('PAH', 'Pendidikan Agama Hindu'), ('PAB', 'Pendidikan Agama Buddha'), ('PAKONG', 'Pendidikan Agama Khonghucu'), ('QURDIS', "Al-Qur'an Hadis"), ('AQIDAH', 'Akidah Akhlak'), ('FIQIH', 'Fikih'), ('SKI', 'Sejarah Kebudayaan Islam'), ('B_ARAB', 'Bahasa Arab'), ('FIS', 'Fisika'), ('KIM', 'Kimia'), ('BIO', 'Biologi'), ('SEJ', 'Sejarah'), ('GEO', 'Geografi'), ('EKO', 'Ekonomi'), ('SOS', 'Sosiologi'), ('MTK_PEM', 'Matematika Peminatan'), ('FIS_PEM', 'Fisika Peminatan'), ('KIM_PEM', 'Kimia Peminatan'), ('BIO_PEM', 'Biologi Peminatan'), ('SEJ_PEM', 'Sejarah Peminatan'), ('GEO_PEM', 'Geografi Peminatan'), ('EKO_PEM', 'Ekonomi Peminatan'), ('SOS_PEM', 'Sosiologi Peminatan'), ('TAFSIR', 'Ilmu Tafsir'), ('HADIS', 'Ilmu Hadis'), ('USULFIQ', 'Ushul Fikih'), ('B_IND_MUL', 'Bahasa dan Sastra Indonesia'), ('B_ING_MUL', 'Bahasa dan Sastra Inggris'), ('B_ASING', 'Bahasa Asing Lainnya'), ('SIMDIG', 'Simulasi Digital'), ('DASDES', 'Dasar Desain Grafis'), ('PEMROG', 'Pemrograman Dasar'), ('JARINGAN', 'Dasar Jaringan Komputer'), ('KWU', 'Kewirausahaan')], max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activesubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formatif_score', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('summatif_score', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='core.activeclassstudent')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='core.activesubject')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Summaries',
            },
        ),
        migrations.CreateModel(
            name='Summative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.activeclassstudent')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.activesubject')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('teacher', 'student'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Berita', 'Berita'), ('Pengumuman', 'Pengumuman'), ('Kegiatan', 'Kegiatan'), ('Prestasi', 'Prestasi'), ('Info', 'Info')], max_length=50, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.album')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.tag'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('nomor_hp', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Nomor telepon tidak valid. Gunakan format Indonesia (08xx...).', regex='^(\\+62|62|0)8[1-9][0-9]{6,10}$')])),
                ('nip', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='NIP harus terdiri dari 18 digit angka.', regex='^\\d{18}$')])),
                ('nuptk', models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='NUPTK harus terdiri dari 16 digit angka.', regex='^\\d{16}$')])),
                ('gelar_depan', models.CharField(blank=True, max_length=50, null=True)),
                ('gelar_belakang', models.CharField(blank=True, max_length=50, null=True)),
                ('job', models.CharField(choices=[('Developer', 'Developer'), ('Administrator', 'Administrator'), ('Agent', 'Agent'), ('Guru', 'Guru')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('active_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='core.activeclub')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='core.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='core.teacher')),
            ],
            options={
                'ordering': ('active_club', 'student'),
            },
        ),
        migrations.AddField(
            model_name='activesubject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_subjects', to='core.teacher'),
        ),
        migrations.AddField(
            model_name='activeclub',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_clubs', to='core.teacher'),
        ),
        migrations.AddField(
            model_name='activeclass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_classes_wali', to='core.teacher'),
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activeyear',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.year'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('mainclassroom', 'name'), name='unique_classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='activeclassstudent',
            unique_together={('activeclass', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='summary',
            unique_together={('student', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='activesubject',
            unique_together={('activeyear', 'subject', 'classroom')},
        ),
        migrations.AlterUniqueTogether(
            name='activeclub',
            unique_together={('activeyear', 'club')},
        ),
        migrations.AddConstraint(
            model_name='activeclass',
            constraint=models.UniqueConstraint(fields=('activeyear', 'classroom'), name='unique_activeclass_year_classroom'),
        ),
        migrations.AddConstraint(
            model_name='activeclass',
            constraint=models.UniqueConstraint(condition=models.Q(('teacher__isnull', False)), fields=('activeyear', 'teacher'), name='unique_wali_per_year'),
        ),
    ]
